In [14]:
import pandas as pd

In [15]:
# Define the path to our data file
path_1 = "mexico-city-real-estate-1.csv"
print(f'Load data from: "{path_1}"')
asf1=pd.read_csv(path_1)
asf1.head()

Load data from: "mexico-city-real-estate-1.csv"

,operation,property_type,place_with_parent_names,lat-lon,price,currency,price_aprox_local_currency,price_aprox_usd,surface_total_in_m2,surface_covered_in_m2,price_usd_per_m2,price_per_m2,floor,rooms,expenses,properati_url
0,sell,apartment,|Miguel Hidalgo|Distrito Federal|México|,"23.634501,-102.552788",5500000.0,MXN,5450245.50,289775.66,NaN,54.0,NaN,101851.851900,NaN,NaN,NaN,http://miguel-hidalgo-df.properati.com.mx/o3zb...
1,sell,house,|Iztapalapa|Distrito Federal|México|,"19.31033,-99.068557",1512000.0,MXN,1498321.97,79661.96,NaN,80.0,NaN,18900.000000,NaN,NaN,NaN,http://iztapalapa.properati.com.mx/q7t0_venta_...
2,sell,apartment,|Tlalpan|Distrito Federal|México|,"19.279771,-99.234597",926667.0,MXN,918284.00,48822.82,NaN,100.0,NaN,9266.670000,NaN,NaN,NaN,http://tlalpan.properati.com.mx/qbi4_venta_dep...
3,sell,apartment,|Miguel Hidalgo|Distrito Federal|México|,"23.634501,-102.552788",6410000.0,MXN,6352013.39,337720.36,NaN,135.0,NaN,47481.481480,NaN,NaN,NaN,http://miguel-hidalgo-df.properati.com.mx/opeq...
4,sell,apartment,|Benito Juárez|Quintana Roo|México|,"21.1902642,-86.8198375",875000.0,USD,16457437.50,875000.00,0.0,263.0,NaN,3326.996198,NaN,NaN,NaN,http://cancun.properati.com.mx/hg4t_venta_depa...

In [16]:
path_2 = "mexico-city-real-estate-2.csv"
print(f'Load data from: "{path_2}"')
asf2=pd.read_csv(path_2)
asf2.head()

Load data from: "mexico-city-real-estate-2.csv"

,operation,property_type,place_with_parent_names,lat-lon,price,currency,price_aprox_local_currency,price_aprox_usd,surface_total_in_m2,surface_covered_in_m2,price_usd_per_m2,price_per_m2,floor,rooms,expenses,properati_url
0,sell,apartment,|Gustavo A. Madero|Distrito Federal|México|,"19.516777,-99.160149",1200000.0,MXN,1189144.46,63223.78,88.0,88.0,718.452046,13636.36364,NaN,NaN,NaN,http://gustavo-a-madero.properati.com.mx/r644_...
1,sell,apartment,|Gustavo A. Madero|Distrito Federal|México|,"19.466724,-99.131614",480000.0,MXN,475657.74,25289.51,NaN,48.0,NaN,10000.00000,NaN,NaN,NaN,http://vallejo.properati.com.mx/mz4c_venta_dep...
2,sell,apartment,|Álvaro Obregón|Distrito Federal|México|,"19.33228,-99.243934",4559261.0,MXN,4518016.68,240211.43,NaN,126.0,NaN,36184.61111,NaN,NaN,NaN,http://alvaro-obregon.properati.com.mx/jh8j_ve...
3,sell,apartment,|Benito Juárez|Quintana Roo|México|,"21.1105772788,-86.8537859927",3808088.0,MXN,3774533.79,200682.34,0.0,171.0,NaN,22269.52047,NaN,NaN,NaN,http://cancun.properati.com.mx/qus8_venta_depa...
4,sell,apartment,|Benito Juárez|Distrito Federal|México|,"19.39365,-99.14769",1730000.0,MXN,1714349.82,91147.61,NaN,100.0,NaN,17300.00000,NaN,NaN,NaN,http://benito-juarez.properati.com.mx/q5my_ven...

In [17]:
column_match= set(asf1)==set(asf2)
if column_match:
    print('The features of the two dataset are same')
    real_estate_df= pd.concat([asf1,asf2], ignore_index=True)
    print('Concatenation Succesful')
else:
    raise Exception('The features of two dataset are not same')

The features of the two dataset are same
Concatenation Succesful

In [18]:
real_estate_df.shape

(9256, 16)

In [19]:
real_estate_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9256 entries, 0 to 9255
Data columns (total 16 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   operation                   9256 non-null   object
 1   property_type               9256 non-null   object
 2   place_with_parent_names     9256 non-null   object
 3   lat-lon                     8289 non-null   object
 4   price                       9090 non-null   float64
 5   currency                    9090 non-null   object
 6   price_aprox_local_currency  9090 non-null   float64
 7   price_aprox_usd             9090 non-null   float64
 8   surface_total_in_m2         3449 non-null   float64
 9   surface_covered_in_m2       8881 non-null   float64
 10  price_usd_per_m2            2410 non-null   float64
 11  price_per_m2                8511 non-null   float64
 12  floor                       613 non-null    float64
 13  rooms                       253 non-null    float64
 14  expenses                    6 non-null      float64
 15  properati_url               9256 non-null   object
dtypes: float64(10), object(6)
memory usage: 1.1+ MB

In [20]:
real_estate_df.dtypes

operation                      object
property_type                  object
place_with_parent_names        object
lat-lon                        object
price                         float64
currency                       object
price_aprox_local_currency    float64
price_aprox_usd               float64
surface_total_in_m2           float64
surface_covered_in_m2         float64
price_usd_per_m2              float64
price_per_m2                  float64
floor                         float64
rooms                         float64
expenses                      float64
properati_url                  object
dtype: object

In [21]:
real_estate_df.isnull().sum()

operation                        0
property_type                    0
place_with_parent_names          0
lat-lon                        967
price                          166
currency                       166
price_aprox_local_currency     166
price_aprox_usd                166
surface_total_in_m2           5807
surface_covered_in_m2          375
price_usd_per_m2              6846
price_per_m2                   745
floor                         8643
rooms                         9003
expenses                      9250
properati_url                    0
dtype: int64

In [22]:
real_estate_df = (real_estate_df.drop(columns=['operation','currency','price','price_aprox_local_currency','price_usd_per_m2','floor','rooms','expenses','properati_url','price_per_m2' ])
                .dropna()
                  )

In [23]:
real_estate_df.place_with_parent_names= real_estate_df.place_with_parent_names.astype('string')
real_estate_df['lat-lon'] = real_estate_df['lat-lon'].astype('string')

real_estate_df=((real_estate_df.assign(state=lambda x: x["place_with_parent_names"].str.split("|", expand=True)[2],
                 lat=lambda x:x['lat-lon'].str.split(',').str[0],
                 lon=lambda x:x['lat-lon'].str.split(',').str[1])
                 )
        .drop(columns=['place_with_parent_names','lat-lon']))

In [24]:

real_estate_df

,property_type,price_aprox_usd,surface_total_in_m2,surface_covered_in_m2,state,lat,lon
4,apartment,875000.00,0.0,263.0,Quintana Roo,21.1902642,-86.8198375
12,apartment,300000.00,1500.0,160.0,Quintana Roo,20.4987828982,-87.2228193283
13,apartment,172446.86,0.0,83.0,Distrito Federal,19.3794059,-99.1591446
15,apartment,115000.00,49.0,49.0,Quintana Roo,21.0511211635,-86.7828512192
20,apartment,70880.12,56.0,56.0,Distrito Federal,19.4024128,-99.0953907
...,...,...,...,...,...,...,...
9229,house,299000.00,0.0,234.0,Quintana Roo,20.2268999,-87.4336011
9233,apartment,53967.66,0.0,63.0,Distrito Federal,19.2990233,-99.0436467
9238,apartment,83264.38,0.0,54.0,Distrito Federal,19.458118,-99.125557
9241,house,2975000.00,762.0,762.0,Distrito Federal,19.420166,-99.220367
9249,house,922232.11,524.0,550.0,Distrito Federal,19.305422,-99.2267203

In [25]:
real_estate_df.to_csv("mexico-real-estate-combined-clean.csv", index=False)